version: '3.2'
services:
    epts-inconsistence-check:
        image: openjdk:8-alpine 
        command: /home/eptssync/scripts/eptssync_inconsistence_check.sh
        container_name: epts-inconsistence-check
        network_mode: host
        environment:
            - origin_app_location_code=qlm_24_julho
            - openmrs_db_host=localhost
            - openmrs_db_port=3308
            - openmrs_db_name=openmrs_24_julho
            - spring_openmrs_datasource_password=root
        working_dir: /home/eptssync
        volumes: 
            - ./release_stuff/etc/eptssync:/home/eptssync
