version: '3.2'
services:
    epts-inconsistence-check:
        image: openjdk:8-alpine 
        command: /home/eptssync/scripts/eptssync_inconsistence_check.sh
        container_name: epts-inconsistence-check
        network_mode: host
        env_file:
            - ./eip.env
        working_dir: /home/eptssync
        volumes: 
            - ./release_stuff/etc/eptssync:/home/eptssync
            - ./logs:/home/eptssync/logs
            - ./release_stuff/scripts:/home/eip/scripts:ro
            - ./shared:/home/eip/shared