version: '3.2'
services:
    openmrs-eip-sender:
        image: openjdk:8-alpine 
        #command: /home/eip/scripts/system_startup.sh && crond -f -l 8 && /home/eip/scripts/eip_tmp.sh
        command: /home/eip/scripts/install.sh 2>&1 | tee -a eip.log
        container_name: openmrs-eip-sender
        ports:
            - "9087:9087"
        network_mode: host
        environment:
            - db_sync_senderId=05_gurue_lioma
            - server_port=9088
            - openmrs_db_host=localhost
            - openmrs_db_port=3308
            - openmrs_db_name=openmrs_lioma
            - spring_openmrs_datasource_password=root
            - spring_artemis_host=localhost
            - spring_artemis_port=8001

        volumes: 
            - ./install.sh:/home/eip/scripts/install.sh
            - ./release_stuff/:/home/eip_setup/:ro
        restart: unless-stopped
