version: '3.2'
services:
    openmrs-eip-sender:
        image: openjdk:8-alpine 
        command: /home/eip/scripts/install.sh
        container_name: openmrs-eip-sender
        network_mode: host
        env_file:
            - ./eip.env
        working_dir: /home/eip
        volumes: 
            - ./install.sh:/home/eip/scripts/install.sh
            - ./:/home/openmrs-eip-docker/:ro
            - ./shared:/home/eip/shared
            - ./release_stuff/ssmpt.conf:/etc/ssmtp/ssmtp.conf
        restart: unless-stopped
