version: '3.2'
services:
    openmrs-eip-sender:
        image: openjdk:8-alpine 
        command: /home/eip/scripts/install.sh 2>&1 | tee -a /home/eip/eip.log
        container_name: openmrs-eip-sender
        ports:
            - "9087:9087"
        network_mode: host
        environment:
            - db_sync_senderId=22_qlm_24_julho
            - server_port=9088
            - openmrs_db_host=localhost
            - openmrs_db_port=3308
            - openmrs_db_name=openmrs_24_julho
            - spring_openmrs_datasource_password=root
            - spring_artemis_host=localhost
            - spring_artemis_port=8001
        working_dir: /home/eip
        volumes: 
            - ./install.sh:/home/eip/scripts/install.sh
            - ./:/home/openmrs-eip-docker/:ro
            - ./logs/:/home/eip/logs
            - ./release_stuff/ssmpt.conf:/etc/ssmtp/ssmtp.conf
        restart: unless-stopped
